// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokedexMeteoApi.Infrastructure;

#nullable disable

namespace PokedexMeteoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PokedexMeteoApi.Domain.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dracaufeu",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pikachu",
                            Type = "Electric"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Psykokwak",
                            Type = "Psychic"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Magicarpe",
                            Type = "Water"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
